import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { Big_Shoulders_Inline_Display, Inter } from "next/font/google";
import Link from "next/link";
import Head from "next/head";
import { useRefresh } from "@/lib/useRefresh";
import { useRouter } from "next/router";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  adjustFontFallback: false,
});

const big_shoulders = Big_Shoulders_Inline_Display({
  subsets: ["latin"],
  variable: "--font-big_shoulders-one",
  adjustFontFallback: false,
});

/**
 * TODO:
 * - SVG drawing
 * - SVG follow path
 * - 3D (react three fiber)
 */
const examples = [
  "keyframes",
  "drag",
  "drag-motion-values",
  "scroll-trigger",
  "layout",
  "shared-layout-presence",
  "variants",
  "sequences",
  "arcs",
] as const;

export default function App({ Component, pageProps }: AppProps) {
  const { refreshButton, key } = useRefresh();
  const router = useRouter();

  return (
    <div key={key}>
      <Head>
        <title>framer motion sandbox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${inter.variable} ${big_shoulders.variable} font-sans`}>
        {refreshButton}

        <div className="fixed top-0 flex flex-wrap gap-x-5 p-3">
          {examples.map((example) => (
            <Link
              key={example}
              href={`/${example}`}
              className={`inline-block p-1 text-zinc-300 hover:underline ${router.pathname === `/${example}` ? "underline" : ""}`}
            >
              {example}
            </Link>
          ))}
        </div>

        <Component {...pageProps} />
      </main>
    </div>
  );
}
